# Generated by Django 2.2 on 2020-04-22 06:49

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('query', models.CharField(default='', max_length=156)),
                ('relevanceKeywords', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('pipeline_step', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(default='', max_length=50)),
                ('text', models.TextField()),
                ('is_relevant', models.BooleanField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Report')),
            ],
        ),
        migrations.CreateModel(
            name='tweetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('keywords', models.TextField(default=None, null=True)),
                ('report', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Report')),
                ('tweets', models.ManyToManyField(blank=True, to='core.Tweet')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
