# Generated by Django 2.2 on 2020-04-26 09:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='sentiment',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
