# Generated by Django 2.2 on 2020-06-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tweet_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tweetCategory_method',
            field=models.CharField(default='', max_length=156),
        ),
    ]
